### ISSUE TITLE
Conda forge

### ISSUE THREAD

**Issue by thewchan** [frankie567/httpx-oauth#277]
Hello! I have successfully put this package on to Conda Forge, and I am extending the invitation for the owner/maintainers of this package to be maintainers on Conda Forge as well. Let me know if you are interested! Thanks.
https://github.com/conda-forge/httpx-oauth-feedstock

**Comment by frankie567** [comment]
Hello @thewchan 👋 

Thank you for this contribution! I must say I'm *completely* unaware of how Conda Forge works 🙃 But I would be happy to be added as a maintainer and try to understand how things work there!

**Comment by frankie567** [comment]
@all-contributors add @thewchan for packaging

**Comment by frankie567** [comment]
@all-contributors add @thewchan for packaging

**Comment by frankie567** [comment]
@all-contributors add @thewchan for platform

**Comment by thewchan** [comment]
@frankie567 Thanks!

Not a lot of work needed at all to be a maintainer on Conda, the initial work is done and the package is available to install via Conda, but when the upstream package is updated and pushed to PyPI, the bots on Conda will automatically make a new PR to mirror the update. If all tests passes the maintainers can merge, if not we can go in to fix the recipe (usually update dependencies etc.), very low-key and self explanatory. I will add you as maintainer over there. Thanks!
