### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by frankie567** [frankie567/httpx-oauth#278]

**Comment by frankie567** [comment]
@all-contributors add @frankie567 for maintenance

**Comment by frankie567** [comment]
@all-contributors add @XaviTorello, @fullonic, @KentonParton, @stepan-chatalyan, @Forst, @williamhatcher for code

**Comment by frankie567** [comment]
@all-contributors add @XaviTorello for code

**Comment by frankie567** [comment]
@all-contributors add @fullonic for code

**Comment by frankie567** [comment]
@Forst Ha, ha, actually, they don't seem to support multiple additions: https://github.com/all-contributors/all-contributors/issues/375

Sorry for the noise, guys 😅

**Comment by frankie567** [comment]
@all-contributors add @KentonParton for code

**Comment by frankie567** [comment]
@all-contributors add @stepan-chatalyan for code

**Comment by Forst** [comment]
I wonder if they require a mention, or `add UserName for code` works as well?

**Comment by frankie567** [comment]
Let's see!

@all-contributors add Forst for code

**Comment by Forst** [comment]
Looks like it worked! Still mentions me in the pull request tho, but that's fine

**Comment by frankie567** [comment]
@all-contributors add @williamhatcher for code

Sorry, Forst 😅
