### ISSUE TITLE
KeyError: 'grant_types_supported'

### ISSUE THREAD

**Issue by LindezaGrey** [frankie567/httpx-oauth#295]
Hi there,
i am using Authelia as an OpenID Connect Provider. The openid_configuration_endpoint response does not inlcude the key "grant_types_supported" so the check 

https://github.com/frankie567/httpx-oauth/blob/ab3d7015ce9d9765bfaaa48750c2eaf730c53fc7/httpx_oauth/clients/openid.py#L32

fails and causes a crash. Since this line is only used for a optional feature later on:

https://github.com/frankie567/httpx-oauth/blob/ab3d7015ce9d9765bfaaa48750c2eaf730c53fc7/httpx_oauth/clients/openid.py#L40

i would suggest to access the openid_configuration in a safer way like so:

```py
refresh_token_supported = "refresh_token" in self.openid_configuration.get(
    "grant_types_supported", []
)

```

instead of

```py
refresh_token_supported = (
    "refresh_token" in self.openid_configuration["grant_types_supported"]
)
```

I am by no means an expert on OAuth, so what is your opinion on this? Is this a legit issue? If not then maybe we could raise a more explicit error instead.

**Comment by frankie567** [comment]
I had a look at the [OpenID Discovery specification](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata), and it seems indeed that `grant_types_supported` is not required.

What you suggest seems indeed a good solution. Would be happy to review a PR with this change.
