### ISSUE TITLE
microsoft not shown in the docs, but appears to be supported...

### ISSUE THREAD

**Issue by jgunstone** [frankie567/httpx-oauth#316]
Just flagging - 
I was reviewing the docs and was disappointed to see there was no Microsoft integration... 
https://github.com/frankie567/httpx-oauth/blob/master/docs/oauth2.md

but then reviewing the code it looks like it is supported ?
https://github.com/frankie567/httpx-oauth/blob/master/httpx_oauth/clients/microsoft.py

cheers

**Comment by frankie567** [comment]
Indeed, that's a miss 😅 PR welcome to add it!
